services:
    # NestJS Application
    app:
        build:
            context: .
            target: production
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            - redis
        restart: unless-stopped
        networks:
            - dep-shield-network

    # Redis Cache
    redis:
        image: redis:7.2-alpine
        ports:
            - '6379:6379'
        restart: unless-stopped
        networks:
            - dep-shield-network

networks:
    dep-shield-network:
        driver: bridge
